// <auto-generated />
using System;
using BistQuant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BistQuant.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(BistQuantDbContext))]
    public partial class BistQuantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BistQuant.Domain.Entities.AlertNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlertSubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertSubscriptionId");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.AlertSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("UserId");

                    b.ToTable("AlertSubscriptions");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualizedReturn")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageWin")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquityCurveJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expectancy")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SharpeRatio")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SortinoRatio")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReturn")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId")
                        .IsUnique();

                    b.ToTable("BacktestResults");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SlippageRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolList")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.HasIndex("SymbolId");

                    b.ToTable("BacktestTrades");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BulletinFetchAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionDate", "AttemptedAtUtc");

                    b.ToTable("BulletinFetchAttempts");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.DailyInstrumentMarketStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChangePercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClosingSessionPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateActionRaw")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSegment")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousLastPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceImportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Suspended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalNumberOfContracts")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalTradedValue")
                        .HasPrecision(24, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalTradedVolume")
                        .HasPrecision(24, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingMethod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Vwap")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceImportId");

                    b.HasIndex("SymbolId", "SessionDate")
                        .IsUnique();

                    b.ToTable("DailyInstrumentMarketStats");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.IndicatorContinuityWarning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorporateActionRaw")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PreviousCloseReported")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousRawCloseInDb")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "SessionDate");

                    b.ToTable("IndicatorContinuityWarnings");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.IndicatorSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ADX14")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ATR14")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageVolume20")
                        .HasPrecision(24, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BollingerLower")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BollingerMiddle")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BollingerUpper")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EMA100")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EMA20")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EMA200")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EMA50")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBreakout")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MACD")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MACDHistogram")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MACDSignal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OBV")
                        .HasPrecision(24, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ROC")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RSI14")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Resistance1")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Resistance2")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SMA20")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SMA200")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SMA50")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StochasticD")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StochasticK")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperTrend")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("SuperTrendDirection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Support1")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Support2")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VWAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VolumeRatio")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("UIX_IndicatorSnapshots_Symbol_Timeframe_Timestamp");

                    b.ToTable("IndicatorSnapshots");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.MarketDataImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastHttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceBarsInserted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceBarsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SupersedesImportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesImportId");

                    b.HasIndex("Provider", "SessionDate");

                    b.HasIndex("Provider", "SessionDate", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("UIX_MarketDataImports_Provider_SessionDate_Sha256");

                    b.ToTable("MarketDataImports");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExecutedSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FilledPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SignalSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLossPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TargetExecutionSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.HasIndex("PortfolioId", "ClientOrderId")
                        .IsUnique()
                        .HasFilter("ClientOrderId IS NOT NULL");

                    b.HasIndex("Status", "TargetExecutionSessionDate")
                        .HasDatabaseName("IX_PaperOrders_Status_TargetExecutionSessionDate");

                    b.ToTable("PaperOrders");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperPortfolio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AutoTradingMaxAllocationPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoTradingMinScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoTradingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaperPortfolios");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.HasIndex("PortfolioId", "SymbolId")
                        .IsUnique();

                    b.ToTable("PaperPositions");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Commission")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PaperOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealizedPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaperOrderId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("SymbolId");

                    b.ToTable("PaperTrades");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PriceBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AdjustedClose")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasPrecision(24, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("UIX_PriceBars_Symbol_Timeframe_Timestamp");

                    b.ToTable("PriceBars");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Signal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MomentumScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RiskRewardRatio")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SignalType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SourceSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StructureScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TakeProfit1")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit2")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrendScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumeScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("SymbolId", "SourceSessionDate", "Timeframe")
                        .IsUnique()
                        .HasDatabaseName("UIX_Signals_Symbol_SessionDate_Timeframe_NoStrategy")
                        .HasFilter("StrategyId IS NULL");

                    b.HasIndex("Timeframe", "CreatedAt", "Score")
                        .HasDatabaseName("IX_Signals_Timeframe_CreatedAt_Score");

                    b.HasIndex("SymbolId", "StrategyId", "SourceSessionDate", "Timeframe")
                        .IsUnique()
                        .HasDatabaseName("UIX_Signals_Symbol_Strategy_SessionDate_Timeframe")
                        .HasFilter("StrategyId IS NOT NULL");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.SignalReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IndicatorValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreContribution")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SignalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SignalId");

                    b.ToTable("SignalReasons");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.StrategyRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComparisonIndicator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SecondaryValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategyRules");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastSeenInBulletinDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Watchlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WatchlistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.HasIndex("WatchlistId", "SymbolId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.WorkerHeartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedCandleClose")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerInstance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timeframe", "CompletedAt");

                    b.ToTable("WorkerHeartbeats");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.AlertNotification", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.AlertSubscription", "AlertSubscription")
                        .WithMany("Notifications")
                        .HasForeignKey("AlertSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertSubscription");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.AlertSubscription", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BistQuant.Domain.Entities.User", "User")
                        .WithMany("AlertSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("Symbol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestResult", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.BacktestRun", "BacktestRun")
                        .WithOne("Result")
                        .HasForeignKey("BistQuant.Domain.Entities.BacktestResult", "BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestRun", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Strategy", "Strategy")
                        .WithMany("BacktestRuns")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestTrade", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacktestRun");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.DailyInstrumentMarketStats", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.MarketDataImport", "SourceImport")
                        .WithMany()
                        .HasForeignKey("SourceImportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceImport");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.IndicatorContinuityWarning", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.IndicatorSnapshot", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany("IndicatorSnapshots")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.MarketDataImport", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.MarketDataImport", "SupersedesImport")
                        .WithMany()
                        .HasForeignKey("SupersedesImportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SupersedesImport");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperOrder", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.PaperPortfolio", "Portfolio")
                        .WithMany("Orders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperPortfolio", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.User", "User")
                        .WithMany("PaperPortfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperPosition", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.PaperPortfolio", "Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperTrade", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.PaperOrder", "PaperOrder")
                        .WithMany()
                        .HasForeignKey("PaperOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BistQuant.Domain.Entities.PaperPortfolio", "Portfolio")
                        .WithMany("Trades")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaperOrder");

                    b.Navigation("Portfolio");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PriceBar", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany("PriceBars")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Signal", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Strategy", "Strategy")
                        .WithMany("Signals")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany("Signals")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.SignalReason", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Signal", "Signal")
                        .WithMany("Reasons")
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.StrategyRule", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Strategy", "Strategy")
                        .WithMany("Rules")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Symbol", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Market", "Market")
                        .WithMany("Symbols")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("BistQuant.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BistQuant.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.AlertSubscription", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.BacktestRun", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Market", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.PaperPortfolio", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Positions");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Signal", b =>
                {
                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("BacktestRuns");

                    b.Navigation("Rules");

                    b.Navigation("Signals");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Symbol", b =>
                {
                    b.Navigation("IndicatorSnapshots");

                    b.Navigation("PriceBars");

                    b.Navigation("Signals");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.User", b =>
                {
                    b.Navigation("AlertSubscriptions");

                    b.Navigation("PaperPortfolios");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("BistQuant.Domain.Entities.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
